
import React from 'react';
import { ArrowLeft, Star, Shield, FileText, Headphones, Bug, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';

const AboutUs = () => {
  const navigate = useNavigate();

  const handleBackClick = () => {
    navigate(-1);
  };

  const handleLinkClick = (type: string) => {
    console.log(`Navigate to ${type}`);
    // Add actual navigation logic here when these pages are created
  };

  return (
    <div className="cosmic-gradient min-h-screen">
      <div className="h-12"></div>

      <header className="px-6 py-4 flex items-center justify-center relative">
        <Button
          variant="ghost"
          size="sm"
          onClick={handleBackClick}
          className="absolute left-6 p-2 rounded-xl hover:bg-violet-100 transition-colors"
        >
          <ArrowLeft className="h-5 w-5 text-violet-700" />
        </Button>
        <h1 className="text-xl font-semibold text-violet-800">About Cosmia</h1>
      </header>

      <main className="px-6">
        {/* Intro Section */}
        <section className="mb-8 text-center">
          <div className="mb-6">
            <div className="w-20 h-20 mx-auto bg-gradient-to-br from-violet-500 to-indigo-600 rounded-3xl flex items-center justify-center shadow-violet mb-4">
              <Star className="h-8 w-8 text-white" />
            </div>
            <h2 className="text-2xl font-bold text-violet-800 mb-3">Cosmia</h2>
            <p className="text-violet-600 font-medium">Your AI-powered daily guide to the stars</p>
          </div>
        </section>

        {/* About Content */}
        <section className="space-y-6 mb-8">
          <div className="bg-white/70 glass-effect rounded-2xl p-6 shadow-lg border border-violet-100">
            <h3 className="text-lg font-semibold text-violet-800 mb-4">About the App</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              Cosmia delivers personalized, AI-generated daily horoscopes designed for astrology enthusiasts aged 20-45. 
              Our intuitive interface focuses on providing meaningful daily insights through the power of artificial intelligence.
            </p>
            <p className="text-sm text-violet-600 font-medium">
              ✨ Powered by advanced AI for personalized horoscope generation
            </p>
          </div>

          <div className="bg-violet-50/80 glass-effect rounded-2xl p-6 border border-violet-200">
            <h3 className="text-lg font-semibold text-violet-800 mb-3">AI & Privacy Disclaimer</h3>
            <p className="text-sm text-gray-600 leading-relaxed">
              Horoscopes are generated by artificial intelligence based on your input and astrological data. 
              All content is provided for entertainment purposes only and should not be considered as professional advice.
            </p>
          </div>

          <div className="bg-white/50 glass-effect rounded-2xl p-6 border border-violet-100">
            <div className="flex justify-between items-center">
              <span className="text-violet-700 font-medium">App Version</span>
              <span className="text-gray-600">1.2.3</span>
            </div>
            <div className="flex justify-between items-center mt-2">
              <span className="text-violet-700 font-medium">Release Date</span>
              <span className="text-gray-600">January 2025</span>
            </div>
          </div>
        </section>

        {/* Links Section */}
        <section className="mb-8">
          <div className="space-y-3">
            <Button
              variant="ghost"
              onClick={() => handleLinkClick('privacy')}
              className="w-full bg-white/80 glass-effect border border-violet-200 rounded-2xl p-4 h-auto flex items-center justify-between hover:bg-white transition-all duration-300 shadow-sm"
            >
              <div className="flex items-center">
                <Shield className="h-5 w-5 text-violet-500 mr-4" />
                <span className="text-violet-800 font-medium">Privacy Policy</span>
              </div>
              <ChevronRight className="h-4 w-4 text-violet-400" />
            </Button>

            <Button
              variant="ghost"
              onClick={() => handleLinkClick('terms')}
              className="w-full bg-white/80 glass-effect border border-violet-200 rounded-2xl p-4 h-auto flex items-center justify-between hover:bg-white transition-all duration-300 shadow-sm"
            >
              <div className="flex items-center">
                <FileText className="h-5 w-5 text-violet-500 mr-4" />
                <span className="text-violet-800 font-medium">Terms of Use</span>
              </div>
              <ChevronRight className="h-4 w-4 text-violet-400" />
            </Button>

            <Button
              variant="ghost"
              onClick={() => handleLinkClick('support')}
              className="w-full bg-white/80 glass-effect border border-violet-200 rounded-2xl p-4 h-auto flex items-center justify-between hover:bg-white transition-all duration-300 shadow-sm"
            >
              <div className="flex items-center">
                <Headphones className="h-5 w-5 text-violet-500 mr-4" />
                <span className="text-violet-800 font-medium">Contact Support</span>
              </div>
              <ChevronRight className="h-4 w-4 text-violet-400" />
            </Button>

            <Button
              variant="ghost"
              onClick={() => handleLinkClick('bug-report')}
              className="w-full bg-white/80 glass-effect border border-violet-200 rounded-2xl p-4 h-auto flex items-center justify-between hover:bg-white transition-all duration-300 shadow-sm"
            >
              <div className="flex items-center">
                <Bug className="h-5 w-5 text-violet-500 mr-4" />
                <span className="text-violet-800 font-medium">Report a Bug</span>
              </div>
              <ChevronRight className="h-4 w-4 text-violet-400" />
            </Button>
          </div>
        </section>
      </main>

      <footer className="px-6 py-8 text-center">
        <div className="pt-4 border-t border-violet-200">
          <p className="text-sm text-violet-600">© 2025 Cosmia. All rights reserved.</p>
        </div>
      </footer>

      <div className="h-8"></div>
    </div>
  );
};

export default AboutUs;
