// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxvlqcrxexnynwxofdys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dmxxY3J4ZXhueW53eG9mZHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTMzMDUsImV4cCI6MjA2ODA4OTMwNX0.cxMY5-FRouzx4hkXfHmH2IrE3_hqJGLAFgFYPN_P2LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});